format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$nodejs\
$python\
$lua\
$rust\
$shell\
$fill\
$cmd_duration \
$jobs \
$time\
$line_break\
$character
"""
[username]
style_root = 'bold red'
style_user = 'bold yellow'
format = '[$user]($style) in'
show_always = false
disabled = false

[hostname]
ssh_only = true
ssh_symbol = '🌐 '
trim_at = '.'
format = '[$ssh_symbol$hostname]($style) in '

[directory]
truncation_length = 4
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold cyan'
disabled = false
read_only = '🔒'
read_only_style = 'red'
truncation_symbol = ''
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
home_symbol = '~'
use_os_path_sep = true

[fill]
symbol = " "

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '


